// Package sshtest is an in-process SSH+SFTP server fixture for integration
// tests: no real VM, no network beyond localhost, no secrets not
// generated by the test itself.
//
// Each accepted "exec" channel runs the received command string through a
// real local /bin/sh -c subprocess (so timeouts, exit codes, truncation,
// and stdin-EOF behavior are all genuine, not simulated), and each
// "subsystem" "sftp" channel is served by pkg/sftp's Server, rooted at a
// real temporary directory that stands in for the remote base.
package sshtest

import (
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

// Server is one running in-process SSH+SFTP fixture.
type Server struct {
	Addr           string // "127.0.0.1:PORT"
	Root           string // temp dir backing the SFTP subsystem
	KeyPEM         []byte // unencrypted PEM private key an authorized client must present
	PublicKey      ssh.PublicKey
	AuthorizedUser string

	listener net.Listener
	wg       sync.WaitGroup
	closed   chan struct{}
}

// Start launches a fixture and registers its shutdown with t.Cleanup.
func Start(t *testing.T) *Server {
	t.Helper()

	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("sshtest: generate key: %v", err)
	}
	signer, err := ssh.NewSignerFromSigner(priv)
	if err != nil {
		t.Fatalf("sshtest: signer: %v", err)
	}
	pemBytes, err := marshalEd25519PrivateKeyPEM(priv)
	if err != nil {
		t.Fatalf("sshtest: marshal key: %v", err)
	}
	_ = pub

	root := t.TempDir()

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("sshtest: listen: %v", err)
	}

	s := &Server{
		Addr:           ln.Addr().String(),
		Root:           root,
		KeyPEM:         pemBytes,
		AuthorizedUser: "testuser",
		listener:       ln,
		closed:         make(chan struct{}),
	}

	sshConfig := &ssh.ServerConfig{
		PublicKeyCallback: func(conn ssh.ConnMetadata, key ssh.PublicKey) (*ssh.Permissions, error) {
			if conn.User() != s.AuthorizedUser {
				return nil, fmt.Errorf("unknown user %q", conn.User())
			}
			if !publicKeysEqual(key, signer.PublicKey()) {
				return nil, fmt.Errorf("unauthorized key")
			}
			return &ssh.Permissions{}, nil
		},
	}
	sshConfig.AddHostKey(signer)
	s.PublicKey = signer.PublicKey()

	s.wg.Add(1)
	go s.acceptLoop(sshConfig)

	t.Cleanup(s.Close)
	return s
}

// Close shuts the fixture down.
func (s *Server) Close() {
	select {
	case <-s.closed:
		return
	default:
		close(s.closed)
	}
	_ = s.listener.Close()
	s.wg.Wait()
}

func (s *Server) acceptLoop(sshConfig *ssh.ServerConfig) {
	defer s.wg.Done()
	for {
		conn, err := s.listener.Accept()
		if err != nil {
			select {
			case <-s.closed:
				return
			default:
				return
			}
		}
		s.wg.Add(1)
		go s.handleConn(conn, sshConfig)
	}
}

func (s *Server) handleConn(conn net.Conn, sshConfig *ssh.ServerConfig) {
	defer s.wg.Done()
	sc, chans, reqs, err := ssh.NewServerConn(conn, sshConfig)
	if err != nil {
		_ = conn.Close()
		return
	}
	defer func() { _ = sc.Close() }()
	go ssh.DiscardRequests(reqs)

	for newCh := range chans {
		if newCh.ChannelType() != "session" {
			_ = newCh.Reject(ssh.UnknownChannelType, "unsupported channel type")
			continue
		}
		ch, chReqs, err := newCh.Accept()
		if err != nil {
			continue
		}
		s.wg.Add(1)
		go s.handleSession(ch, chReqs)
	}
}

type execMsg struct {
	Command string
}

type subsystemMsg struct {
	Subsystem string
}

type exitStatusMsg struct {
	Status uint32
}

func (s *Server) handleSession(ch ssh.Channel, reqs <-chan *ssh.Request) {
	defer s.wg.Done()
	defer func() { _ = ch.Close() }()

	for req := range reqs {
		switch req.Type {
		case "exec":
			var m execMsg
			if err := ssh.Unmarshal(req.Payload, &m); err != nil {
				_ = req.Reply(false, nil)
				continue
			}
			_ = req.Reply(true, nil)
			s.runExec(ch, m.Command)
			return
		case "subsystem":
			var m subsystemMsg
			if err := ssh.Unmarshal(req.Payload, &m); err != nil || m.Subsystem != "sftp" {
				_ = req.Reply(false, nil)
				continue
			}
			_ = req.Reply(true, nil)
			s.runSFTP(ch)
			return
		default:
			if req.WantReply {
				_ = req.Reply(false, nil)
			}
		}
	}
}

// runExec is the real-subprocess backend for "exec" channels: the
// received command string (already built by BuildCommand, i.e. already
// POSIX-quoted argv-equivalent) is handed to a real /bin/sh -c, so exit
// codes, timeouts, and truncation are all genuine.
func (s *Server) runExec(ch ssh.Channel, command string) {
	cmd := exec.Command("/bin/sh", "-c", command)
	cmd.Stdin = nil // immediate EOF for the child's stdin, matching a real sshd
	// A pipeline's grandchildren (e.g. "yes | head") must be killable as
	// a group: a blocked pipeline stage (backpressure once the SSH client
	// stops draining) survives killing just /bin/sh itself, since it was
	// only sh's direct child.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	stdout, _ := cmd.StdoutPipe()
	stderr, _ := cmd.StderrPipe()

	if err := cmd.Start(); err != nil {
		_, _ = fmt.Fprintf(ch.Stderr(), "sshtest: exec: %v\n", err)
		sendExit(ch, 127)
		return
	}

	// Watchdog: if the SSH client stops draining the channel (e.g. it hit
	// its own truncation cap and closed the session), a pipeline stage can
	// be left blocked on a full pipe indefinitely; forcibly killing the
	// whole process group unblocks the local pipe reads that feed it,
	// bounding this fixture's worst case regardless of cause. Real sshd
	// implementations don't need this — it exists only because this is a
	// test double.
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-done:
		case <-time.After(1 * time.Second):
			_ = syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
		}
	}()

	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); _, _ = io.Copy(ch, stdout) }()
	go func() { defer wg.Done(); _, _ = io.Copy(ch.Stderr(), stderr) }()
	wg.Wait()

	err := cmd.Wait()
	code := 0
	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			code = exitErr.ExitCode()
		} else {
			code = 1
		}
	}
	sendExit(ch, code)
}

func sendExit(ch ssh.Channel, code int) {
	_, _ = ch.SendRequest("exit-status", false, ssh.Marshal(&exitStatusMsg{Status: uint32(code)}))
	_ = ch.Close()
}

func (s *Server) runSFTP(ch ssh.Channel) {
	server, err := sftp.NewServer(ch, sftp.WithServerWorkingDirectory(s.Root))
	if err != nil {
		return
	}
	_ = server.Serve()
	_ = server.Close()
}

func publicKeysEqual(a, b ssh.PublicKey) bool {
	return string(a.Marshal()) == string(b.Marshal())
}

func marshalEd25519PrivateKeyPEM(priv ed25519.PrivateKey) ([]byte, error) {
	block, err := ssh.MarshalPrivateKey(priv, "")
	if err != nil {
		return nil, err
	}
	return pem.EncodeToMemory(block), nil
}

// WriteKeyFile writes the fixture's unencrypted test private key to a new
// file under t.TempDir() and returns its path.
func WriteKeyFile(t *testing.T, s *Server) string {
	t.Helper()
	path := t.TempDir() + "/id_test"
	if err := os.WriteFile(path, s.KeyPEM, 0o600); err != nil {
		t.Fatalf("sshtest: write key file: %v", err)
	}
	return path
}

// SplitHostPort returns the fixture's listening host and port, for
// building a config.VM without importing internal/config here (which
// would create an import cycle with packages that themselves import
// sshtest for their own tests).
func (s *Server) SplitHostPort() (host string, port int) {
	h, p, err := net.SplitHostPort(s.Addr)
	if err != nil {
		return "127.0.0.1", 0
	}
	var portNum int
	_, _ = fmt.Sscanf(p, "%d", &portNum)
	return h, portNum
}
